### ISSUE TITLE
please solve this error

### ISSUE THREAD

**Issue by 23BCA284** [vtcbca/csv-file-program-23BCA284#2]
![Screenshot (9)](https://github.com/user-attachments/assets/86896c29-19d1-479c-b8e4-c5e84a94c0c9)

**Comment by 23bca274** [comment]
Take 5 value and assign that value with subject name after for loop and print total and percentage... If you still don't understand... Check my program " result(csv) " file and try again

**Comment by 23BCA284** [comment]
it's working,Thank you
